import type { ProductSection } from '@/shared/lib/types/product'

export const mockProductSections: ProductSection[] = [
  {
    id: 'promotions',
    title: 'Акции',
    linkTitle: 'Все акции',
    products: [
      {
        id: '1',
        title: 'Г/Ц Блинчики с мясом вес, Россия',
        price: '44,50',
        cardPrice: '50,50',
        badge: '-50%',
        rating: 2,
        hasCardPrice: true,
        isFavorite: true,
        hasSaleBadge: true,
        image: `/products/product-1.png`,
      },
      {
        id: '2',
        title: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
        price: '44,50',
        cardPrice: '50,50',
        badge: '-50%',
        rating: 3,
        hasCardPrice: true,
        isFavorite: false,
        hasSaleBadge: true,
        image: `/products/product-2.png`,
      },
      {
        id: '3',
        title: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...',
        price: '44,50',
        cardPrice: '50,50',
        badge: '-50%',
        rating: 5,
        hasCardPrice: true,
        isFavorite: false,
        hasSaleBadge: true,
        image: `/products/product-3.png`,
      },
      {
        id: '4',
        title: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
        price: '44,50',
        cardPrice: '50,50',
        badge: '-50%',
        rating: 4.1,
        hasCardPrice: true,
        isFavorite: false,
        hasSaleBadge: true,
        image: `/products/product-4.png`,
      },
    ],
  },
  {
    id: 'newProducts',
    title: 'Новинки',
    linkTitle: 'Все новинки',
    products: [
      {
        id: '1',
        title: 'Г/Ц Блинчики с мясом вес, Россия',
        price: '44,50',
        rating: 2,
        hasCardPrice: true,
        isFavorite: true,
        hasSaleBadge: false,
        image: `/products/product-1.png`,
      },
      {
        id: '2',
        title: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
        price: '44,50',
        rating: 3,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-2.png`,
      },
      {
        id: '3',
        title: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...',
        price: '44,50',
        rating: 5,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-3.png`,
      },
      {
        id: '4',
        title: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
        price: '44,50',
        rating: 4.1,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-4.png`,
      },
    ],
  },
  {
    id: 'buyBefore',
    title: 'Покупали раньше',
    linkTitle: 'Все покупки',
    products: [
      {
        id: '1',
        title: 'Г/Ц Блинчики с мясом вес, Россия',
        price: '44,50',
        rating: 2,
        hasCardPrice: true,
        isFavorite: true,
        hasSaleBadge: false,
        image: `/products/product-1.png`,
      },
      {
        id: '2',
        title: 'Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...',
        price: '44,50',
        rating: 3,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-2.png`,
      },
      {
        id: '3',
        title: 'Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...',
        price: '44,50',
        rating: 5,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-3.png`,
      },
      {
        id: '4',
        title: 'Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...',
        price: '44,50',
        rating: 4.1,
        hasCardPrice: false,
        isFavorite: false,
        hasSaleBadge: false,
        image: `/products/product-4.png`,
      },
    ],
  },
]
